/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResidentialRouteImport } from './routes/residential'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DroneCleaningRouteImport } from './routes/drone-cleaning'
import { Route as DockRouteImport } from './routes/dock'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas/index'
import { Route as ServiceAreasWestAshleyRouteImport } from './routes/service-areas/west-ashley'
import { Route as ServiceAreasMountPleasantRouteImport } from './routes/service-areas/mount-pleasant'
import { Route as ServiceAreasJamesIslandRouteImport } from './routes/service-areas/james-island'
import { Route as ServiceAreasDowntownCharlestonRouteImport } from './routes/service-areas/downtown-charleston'
import { Route as ServiceAreasDanielIslandRouteImport } from './routes/service-areas/daniel-island'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialRoute = ResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DroneCleaningRoute = DroneCleaningRouteImport.update({
  id: '/drone-cleaning',
  path: '/drone-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const DockRoute = DockRouteImport.update({
  id: '/dock',
  path: '/dock',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasWestAshleyRoute = ServiceAreasWestAshleyRouteImport.update({
  id: '/service-areas/west-ashley',
  path: '/service-areas/west-ashley',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasMountPleasantRoute =
  ServiceAreasMountPleasantRouteImport.update({
    id: '/service-areas/mount-pleasant',
    path: '/service-areas/mount-pleasant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasJamesIslandRoute = ServiceAreasJamesIslandRouteImport.update({
  id: '/service-areas/james-island',
  path: '/service-areas/james-island',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasDowntownCharlestonRoute =
  ServiceAreasDowntownCharlestonRouteImport.update({
    id: '/service-areas/downtown-charleston',
    path: '/service-areas/downtown-charleston',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAreasDanielIslandRoute =
  ServiceAreasDanielIslandRouteImport.update({
    id: '/service-areas/daniel-island',
    path: '/service-areas/daniel-island',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/dock': typeof DockRoute
  '/drone-cleaning': typeof DroneCleaningRoute
  '/gallery': typeof GalleryRoute
  '/residential': typeof ResidentialRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/service-areas/daniel-island': typeof ServiceAreasDanielIslandRoute
  '/service-areas/downtown-charleston': typeof ServiceAreasDowntownCharlestonRoute
  '/service-areas/james-island': typeof ServiceAreasJamesIslandRoute
  '/service-areas/mount-pleasant': typeof ServiceAreasMountPleasantRoute
  '/service-areas/west-ashley': typeof ServiceAreasWestAshleyRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/dock': typeof DockRoute
  '/drone-cleaning': typeof DroneCleaningRoute
  '/gallery': typeof GalleryRoute
  '/residential': typeof ResidentialRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/service-areas/daniel-island': typeof ServiceAreasDanielIslandRoute
  '/service-areas/downtown-charleston': typeof ServiceAreasDowntownCharlestonRoute
  '/service-areas/james-island': typeof ServiceAreasJamesIslandRoute
  '/service-areas/mount-pleasant': typeof ServiceAreasMountPleasantRoute
  '/service-areas/west-ashley': typeof ServiceAreasWestAshleyRoute
  '/service-areas': typeof ServiceAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/dock': typeof DockRoute
  '/drone-cleaning': typeof DroneCleaningRoute
  '/gallery': typeof GalleryRoute
  '/residential': typeof ResidentialRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/service-areas/daniel-island': typeof ServiceAreasDanielIslandRoute
  '/service-areas/downtown-charleston': typeof ServiceAreasDowntownCharlestonRoute
  '/service-areas/james-island': typeof ServiceAreasJamesIslandRoute
  '/service-areas/mount-pleasant': typeof ServiceAreasMountPleasantRoute
  '/service-areas/west-ashley': typeof ServiceAreasWestAshleyRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commercial'
    | '/contact'
    | '/dock'
    | '/drone-cleaning'
    | '/gallery'
    | '/residential'
    | '/services'
    | '/team'
    | '/service-areas/daniel-island'
    | '/service-areas/downtown-charleston'
    | '/service-areas/james-island'
    | '/service-areas/mount-pleasant'
    | '/service-areas/west-ashley'
    | '/service-areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commercial'
    | '/contact'
    | '/dock'
    | '/drone-cleaning'
    | '/gallery'
    | '/residential'
    | '/services'
    | '/team'
    | '/service-areas/daniel-island'
    | '/service-areas/downtown-charleston'
    | '/service-areas/james-island'
    | '/service-areas/mount-pleasant'
    | '/service-areas/west-ashley'
    | '/service-areas'
  id:
    | '__root__'
    | '/'
    | '/commercial'
    | '/contact'
    | '/dock'
    | '/drone-cleaning'
    | '/gallery'
    | '/residential'
    | '/services'
    | '/team'
    | '/service-areas/daniel-island'
    | '/service-areas/downtown-charleston'
    | '/service-areas/james-island'
    | '/service-areas/mount-pleasant'
    | '/service-areas/west-ashley'
    | '/service-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  DockRoute: typeof DockRoute
  DroneCleaningRoute: typeof DroneCleaningRoute
  GalleryRoute: typeof GalleryRoute
  ResidentialRoute: typeof ResidentialRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  ServiceAreasDanielIslandRoute: typeof ServiceAreasDanielIslandRoute
  ServiceAreasDowntownCharlestonRoute: typeof ServiceAreasDowntownCharlestonRoute
  ServiceAreasJamesIslandRoute: typeof ServiceAreasJamesIslandRoute
  ServiceAreasMountPleasantRoute: typeof ServiceAreasMountPleasantRoute
  ServiceAreasWestAshleyRoute: typeof ServiceAreasWestAshleyRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential': {
      id: '/residential'
      path: '/residential'
      fullPath: '/residential'
      preLoaderRoute: typeof ResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drone-cleaning': {
      id: '/drone-cleaning'
      path: '/drone-cleaning'
      fullPath: '/drone-cleaning'
      preLoaderRoute: typeof DroneCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock': {
      id: '/dock'
      path: '/dock'
      fullPath: '/dock'
      preLoaderRoute: typeof DockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/west-ashley': {
      id: '/service-areas/west-ashley'
      path: '/service-areas/west-ashley'
      fullPath: '/service-areas/west-ashley'
      preLoaderRoute: typeof ServiceAreasWestAshleyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/mount-pleasant': {
      id: '/service-areas/mount-pleasant'
      path: '/service-areas/mount-pleasant'
      fullPath: '/service-areas/mount-pleasant'
      preLoaderRoute: typeof ServiceAreasMountPleasantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/james-island': {
      id: '/service-areas/james-island'
      path: '/service-areas/james-island'
      fullPath: '/service-areas/james-island'
      preLoaderRoute: typeof ServiceAreasJamesIslandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/downtown-charleston': {
      id: '/service-areas/downtown-charleston'
      path: '/service-areas/downtown-charleston'
      fullPath: '/service-areas/downtown-charleston'
      preLoaderRoute: typeof ServiceAreasDowntownCharlestonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/daniel-island': {
      id: '/service-areas/daniel-island'
      path: '/service-areas/daniel-island'
      fullPath: '/service-areas/daniel-island'
      preLoaderRoute: typeof ServiceAreasDanielIslandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  DockRoute: DockRoute,
  DroneCleaningRoute: DroneCleaningRoute,
  GalleryRoute: GalleryRoute,
  ResidentialRoute: ResidentialRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  ServiceAreasDanielIslandRoute: ServiceAreasDanielIslandRoute,
  ServiceAreasDowntownCharlestonRoute: ServiceAreasDowntownCharlestonRoute,
  ServiceAreasJamesIslandRoute: ServiceAreasJamesIslandRoute,
  ServiceAreasMountPleasantRoute: ServiceAreasMountPleasantRoute,
  ServiceAreasWestAshleyRoute: ServiceAreasWestAshleyRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
